export const mutators: { [x: string]: string[] } = {
  game_mode: [
    "Soccar",
    "Hoops",
    "Dropshot",
    "Snowday",
    "Rumble",
    "Heatseeker",
    "Gridiron",
    "Knockout",
  ],
  match_length: ["5 Minutes", "10 Minutes", "20 Minutes", "Unlimited"],
  max_score: [
    "Unlimited",
    "1 Goal",
    "3 Goals",
    "5 Goals",
    "7 Goals",
    "10 Goals",
    "20 Goals",
    "30 Goals",
    "40 Goals",
    "50 Goals",
    "60 Goals",
    "70 Goals",
    "80 Goals",
    "90 Goals",
    "100 Goals",
    "151 Goals",
  ],
  multi_ball: ["1", "2", "4", "6"],
  overtime: ["Unlimited", "5 Max First Score", "5 Max Random Team"],
  series_length: ["Unlimited", "3 Games", "5 Games", "7 Games"],
  game_speed: ["Default", "Slo Mo", "Time Warp"],
  ball_max_speed: ["Default", "Slow", "Fast", "Super Fast"],
  ball_type: [
    "Default",
    "Cube",
    "Puck",
    "Basketball",
    "Beachball",
    "Anniversary",
    "Haunted",
    "Nike Skin",
    "Spooky Cube",
    "Egg",
    "Player Seeking",
    "Dropshot",
    "Score Absorb",
    "FIFA Club World Cup Ball",
    "Pizza Puck",
    "Soccer",
    "Spooky Balloon",
  ],
  ball_weight: [
    "Default",
    "Light",
    "Heavy",
    "Super Light",
    "Curve Ball",
    "Beach Ball Curve",
    "Magnus FutBall",
    "Soccar Ball Curve",
    "Balloon",
  ],
  ball_size: ["Default", "Small", "Medium", "Large", "Gigantic"],
  ball_bounciness: ["Default", "Low", "High", "Super High", "Lowish"],
  boost_amount: [
    "Default",
    "Unlimited",
    "Slow Recharge",
    "Rapid Recharge",
    "None",
  ],
  rumble: [
    "Off",
    "Default",
    "Slow",
    "Civilized",
    "Destruction Derby",
    "Spring Loaded",
    "Spikes Only",
    "Spike Rush",
    "Haunted Ball Beam",
    "Tactical",
    "Batman Rumble",
    "Grappling Only",
    "Haymaker Only",
    "Spike Rush Force",
    "Rock-Paper-Scissors",
  ],
  boost_strength: ["1x", "1.5x", "2x", "5x", "10x"],
  gravity: ["Default", "Low", "High", "Super High", "Reverse"],
  demolish: [
    "Default",
    "Disabled",
    "Friendly Fire",
    "On Contact",
    "On Contact FF",
    "On Ball Contact",
    "On Ball Contact FF",
    "On Ball Contact Silent",
    "On Ball Contact FF Silent",
  ],
  respawn_time: ["3 Seconds", "2 Seconds", "1 Second", "Disable Goal Reset"],
  max_time: [
    "Unlimited",
    "1 Minute",
    "2 Minutes",
    "3 Minutes",
    "4 Minutes",
    "5 Minutes",
    "6 Minutes",
    "7 Minutes",
    "8 Minutes",
    "9 Minutes",
    "10 Minutes",
    "11 Minutes",
    "12 Minutes",
    "13 Minutes",
    "14 Minutes",
    "15 Minutes",
  ],
  game_event: ["Default", "Haunted", "Rugby"],
  audio: ["Default", "Haunted"],
  ball_gravity: ["Default", "Low", "High", "Super High"],
  territory: ["Off", "On"],
  stale_ball: ["Unlimited", "30 Seconds"],
  jump: ["Default", "Grounded", "2", "3", "4", "Unlimited", "No Jumps"],
  dodge_timer: ["1.25 Seconds", "2 Seconds", "3 Seconds", "Unlimited"],
  possession_score: ["Off", "1 Second", "2 Seconds", "3 Seconds"],
  demolish_score: ["0", "1", "2", "3"],
  normal_goal_score: ["1", "0", "2", "3", "5", "10"],
  aerial_goal_score: ["1", "0", "2", "3", "5", "10"],
  assist_goal_score: ["0", "1", "2", "3"],
  input_restriction: ["None", "Backwards"],
  scoring_rule: ["Default", "Disable Goal Scoring"],
  tri_tip_mode: ["Off", "Tritip"],
  locked_damage_phase: ["Default", "High"],
  spawn_demoball: ["Off", "On"],
  boost_restriction: ["Default", "Aerial Only"],
  keep_up_rules: ["Off", "Enabled (Increment)", "Enabled"],
  match_admin: ["Off", "On"],
};
